package zad1.zad1;


import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.ArrayList;
import java.util.List;


public class wlasciciel implements wlascicielInterface<osoba>{

	Connection conn;
	private String url = "jdbc:hsqldb:hsql://localhost/workdb";

	String createTable=
			"CREATE TABLE Osoba(id bigint GENERATED BY DEFAULT AS IDENTITY," +
			" name varchar(20), pesel varchar(20))";
 
	Statement statement;
	PreparedStatement addPersonStatement;
	PreparedStatement deletePersonStatement;
	PreparedStatement getAllPersonsStatement;
	PreparedStatement getPersonByIdStatement;
	public wlasciciel()
	{
		try {
			conn=DriverManager.getConnection(url);
			statement = conn.createStatement();

			ResultSet rs = conn.getMetaData().getTables(null, null, null,
					null);
			boolean tableExists = false;
			while (rs.next()) {
				if ("Osoba".equalsIgnoreCase(rs.getString("TABLE_NAME"))) {
					tableExists = true;
					break;
				}
			}

			if(!tableExists)
			{
				statement.executeUpdate(createTable);

			}

			addPersonStatement = conn
					.prepareStatement(
							"INSERT INTO Osoba (name, pesel) " +
							"VALUES (?, ?)");
			deletePersonStatement=conn
					.prepareStatement("DELETE From Osoba WHERE name=?");
			getAllPersonsStatement = conn
					.prepareStatement("SELECT * FROM Osoba");
			getPersonByIdStatement=conn
					.prepareStatement("SELECT * FROM Osoba WHERE id=?");

		} catch (SQLException e) {

			e.printStackTrace();
		}
	}


  @Override
	public osoba get(int id) {
		try {
			getPersonByIdStatement.setInt(1, id);
			ResultSet rs= getPersonByIdStatement.executeQuery();
			while(rs.next())
			{
				return new osoba(rs.getString("Name"),rs.getString("pesel"));
			}

		} catch (SQLException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		}

		return null;
	}

	@Override
	public List<osoba> getAll() {
		List<osoba> result= new ArrayList<osoba>();

		try {
			ResultSet rs= getAllPersonsStatement.executeQuery();
			while(rs.next())
			{
				osoba p = new osoba();
				p.setName(rs.getString("name"));
				p.setPesel(rs.getString("pesel"));
				result.add(p);
			}

		} catch (SQLException e) {
	
			e.printStackTrace();
		}
		return result;
	}

	@Override
	public boolean save(osoba obj) {
		try {
			addPersonStatement.setString(1, obj.getName());
			addPersonStatement.setString(2, obj.getPesel());
			return addPersonStatement.execute();
		} catch (SQLException e) {
			e.printStackTrace();
		}
		return false;
	}

	@Override
	public boolean delete(osoba obj) {

		try {
			deletePersonStatement.setString(1, obj.getName());
			deletePersonStatement.executeUpdate();
		} catch (SQLException e) {
			e.printStackTrace();
		}

		return false;
	}

}